spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: none
        default_batch_fetch_size: 1000

discord:
  webhook:
    url: https://discord.com/api/webhooks/1372426888278183988/DsQlUXaoj6yysZToho3eBis6h1FE-1-tey771P_eMVyKpVIqhW5iL_T2j4oX2_9cMzCR