spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/umc8th
    username: root
    password: emfo!@0717
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  data:
    web:
      pageable:
        one-indexed-parameters: true

jwt:
  token:
    secretKey: umceightfightingjwttokenauthentication
    expiration:
      access: 14400000